# Generated by Django 5.0.3 on 2024-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
